### ISSUE TITLE
speeding up pull requests

### ISSUE THREAD

**Issue by edublancas** [ploomber/pkgmt#31]
when reviewing pull requests, the reviewer must manually check a lot of stuff. we could write a script to automate this.

- entries added to CHANGELOG.md

**Comment by edublancas** [comment]
wil start testing this in some repos

```yaml
name: check-pr

on: [pull_request]

jobs:
  # check that the changelog has been modified. If not, post a message to the PR
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check PR
        id: changelog
        continue-on-error: true
        run: |

          # check if changelog has been modified
          git fetch origin $GITHUB_BASE_REF:$GITHUB_BASE_REF --depth 1
          git --no-pager diff --name-only --diff-filter=ACMRT $GITHUB_BASE_REF | grep CHANGELOG.md

      - uses: actions/github-script@v5
        if: steps.changelog.outcome == 'failure'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'changelog unmodified!'
            })
```
