### ISSUE TITLE
change versioneer settings via pyproject.toml

### ISSUE THREAD

**Issue by edublancas** [ploomber/pkgmt#63]
once we finish: https://github.com/ploomber/pkgmt/pull/60

we should allow users to customize the behavior of `pkgmt version`

```toml
[tool.pkgmt]
github = "project/repository" 
version = {version_file: "/path/to/version_file.py", tag: false, push: false}
```
