### ISSUE TITLE
`pkgmt` `format` and `lint` exclude command overrides `pyproject.toml`

### ISSUE THREAD

**Issue by mehtamohit013** [ploomber/pkgmt#66]
Whenever a user specifies excluded directory in `pyproject.toml` for `black` like:

```toml
[tool.black]
extend-exclude = "ploomber_add"
```
`black . --extend-exclude ''` overrides the `extend-exclude` in `pyproject.toml`
